BLOCK_PROMPT = (
    "PERHATIAN: gambar ini SUDAH diberi GARIS bantu -- 5 GARIS MERAH "
    "VERTIKAL membagi gambar (dari atas sampai bawah) menjadi PERSIS 6 "
    "KOLOM, dan 2 GARIS CYAN HORIZONTAL menandai batas ATAS & BAWAH baris "
    "\"Lost time\" yang harus kamu baca (ABAIKAN SEPENUHNYA area di luar 2 "
    "garis cyan ini, walau ada teks/kotak/label jam lain kelihatan di situ "
    "-- itu BUKAN bagian dari tugasmu). ANGKA HIJAU 1-6 di dekat garis cyan "
    "atas menandai nomor tiap kolom.\n\n"
    "PERHATIAN JUGA: kadang operator menulis 2 kode berdekatan di 2 kotak "
    "bersebelahan (mis. \"6a\" di kotak ini, \"5b\" di kotak sebelahnya) -- "
    "JANGAN menyalin kode dari kotak tetangga hanya krn bentuknya mirip. "
    "Tiap kotak (antar garis merah, dalam rentang garis cyan) punya isi "
    "independen, baca HANYA apa yg benar-benar ada di kotak itu sendiri.\n\n"
    "CARA KERJA WAJIB: proses SATU PER SATU, kolom demi kolom, JANGAN "
    "mengumpulkan semua kode dulu baru menyusunnya bebas. Untuk TIAP "
    "kolom (1 sampai 6): lihat KHUSUS area yang ditandai angka hijau "
    "tsb (di antara garis merah kiri & kanannya), lalu putuskan APAKAH "
    "kotak ITU SAJA berisi kode, huruf 'x', atau kosong -- TANPA "
    "mempertimbangkan kotak lain terlebih dulu. Kalau kolom 1-4 kosong "
    "dan kode cuma ada di kolom 5,6 -- maka kolom_1 s.d kolom_4 HARUS "
    "null, dan kode itu HARUS ditulis di kolom_5/kolom_6, BUKAN "
    "dipindah ke kolom_1/kolom_2 hanya krn itu kode PERTAMA yang kamu "
    "temukan.\n\n"
    "Kembalikan HANYA JSON (tanpa teks lain, tanpa markdown code fence), "
    "PERSIS format ini -- SATU KEY UNTUK SATU KOLOM (jangan pakai array):\n"
    "{\n"
    "  \"jam_label\": \"07.00 - 08.00\",\n"
    "  \"kolom_1\": null,\n"
    "  \"kolom_2\": null,\n"
    "  \"kolom_3\": null,\n"
    "  \"kolom_4\": null,\n"
    "  \"kolom_5\": \"6a\",\n"
    "  \"kolom_6\": \"5b\"\n"
    "}\n\n"
    "Tiap \"kolom_N\" adalah SALAH SATU dari 3 bentuk berikut:\n"
    "  \"6a\"   <- kalau ADA tulisan tangan (1 digit angka 0-8 opsional + "
    "1 huruf kecil)\n"
    "  \"x\"    <- HANYA kalau isinya HURUF 'x' SAJA (penanda akhir rentang "
    "masalah panjang, BUKAN kode kategori biasa)\n"
    "  null    <- kalau kotak ini KOSONG (tidak ada coretan sama sekali)\n\n"
    "ATURAN:\n"
    "1. \"jam_label\": transkrip label jam persis seperti tertulis di crop "
    "ini (utk verifikasi crop yg benar terkirim).\n"
    "2. WAJIB ada PERSIS 6 key: \"kolom_1\" s.d \"kolom_6\" -- semua HARUS "
    "ada di JSON walau isinya null, jangan dihilangkan.\n"
    "3. PERINGATAN KERAS soal \"x\": kode ini SANGAT LANGKA -- biasanya "
    "HANYA MUNCUL SATU KALI (atau nol kali) di SELURUH 48 kotak dalam 1 "
    "shift (8 blok x 6 kotak), BUKAN sekali per blok. Kalau kamu berpikir "
    "lebih dari 1 dari 6 kolom di crop ini adalah \"x\", itu HAMPIR PASTI "
    "SALAH -- kamu sedang menjadikan \"x\" jawaban default saat ragu. Kalau "
    "ragu antara \"x\" dan kosong (null), SELALU pilih null.\n"
    "4. Huruf kecil \"l\" BEDA dari angka \"1\" -- perhatikan bentuknya.\n"
    "5. JANGAN mengarang isi kotak. Ragu, tulisan tidak jelas, atau kotak "
    "terlihat kosong -> null. Defaultmu SELALU null kalau tidak yakin, "
    "TIDAK PERNAH \"x\".\n"
    "6. Nilai tiap \"kolom_N\" WAJIB JSON string bertanda kutip ganda "
    "(termasuk kalau kebetulan cuma angka \"0\"), atau null (tanpa kutip) "
    "kalau kosong.\n"
    "7. Output HARUS JSON valid saja, PERSIS 7 field: \"jam_label\" + "
    "\"kolom_1\" s.d \"kolom_6\".\n"
)