BLOCK_PROMPT = (
    "Kamu melihat SATU CROP dari form kertas industri (Laporan Proses Drawing "
    "Harian). Crop ini berisi 1 label rentang jam di bagian ATAS gambar "
    "(contoh: \"07.00 - 08.00\"), dan tepat DI BAWAH label itu ada SATU BARIS "
    "berisi 6 KOTAK KECIL (kotak \"Lost time\", 1 kotak = 10 menit), dibatasi "
    "garis horizontal tebal di bagian bawah baris tsb.\n\n"
    "PENTING -- crop ini SENGAJA diberi ruang lebih (padding) supaya kamu "
    "bisa lihat konteks di sekitarnya. Karena itu:\n"
    "- Di BAWAH garis horizontal tebal, mungkin ada teks/kotak lain (label "
    "jam & baris BERIKUTNYA) -- ABAIKAN SEPENUHNYA, itu BUKAN bagian dari "
    "tugasmu.\n"
    "- Di kiri/kanan gambar, mungkin ada SEBAGIAN/POTONGAN kotak dari blok "
    "jam TETANGGA (bukan 6 kotak yg dimaksud) -- ABAIKAN, jangan dihitung "
    "atau dibaca.\n"
    "- HANYA baca 6 kotak yang berada TEPAT di bawah label jam yang tertulis "
    "di bagian atas gambar ini, dan tepat di atas garis horizontal tebal "
    "penutup baris.\n\n"
    "Kembalikan HANYA JSON (tanpa teks lain, tanpa markdown code fence), "
    "PERSIS format ini:\n"
    "{\"jam_label\": \"07.00 - 08.00\", \"kotak\": [k1, k2, k3, k4, k5, k6]}\n\n"
    "ATURAN:\n"
    "1. \"jam_label\": transkrip label jam persis seperti tertulis di crop "
    "ini (utk verifikasi crop yg benar terkirim).\n"
    "2. \"kotak\" WAJIB PERSIS 6 elemen, urutan KIRI ke KANAN, tidak boleh "
    "kurang/lebih dari 6 walau kotak di tepi terlihat terpotong (kotak "
    "terpotong itu BUKAN bagian dari 6 kotak ini, jangan dimasukkan).\n"
    "3. Tiap elemen: 1 digit angka (0-8) opsional + 1 huruf kecil (mis. "
    "\"6a\", \"2f\", \"0\"), ATAU huruf \"x\" sendirian (penanda akhir "
    "rentang masalah panjang), ATAU null kalau kotak itu KOSONG.\n"
    "4. Huruf kecil \"l\" BEDA dari angka \"1\" -- perhatikan bentuknya.\n"
    "5. JANGAN mengarang isi kotak. Ragu atau kotak terlihat kosong -> null.\n"
    "6. JANGAN menyalin kode dari 1 kotak ke kotak tetangganya hanya krn "
    "bentuknya mirip -- tiap kotak punya isi independen, walau kadang "
    "operator menulis 2 kode berdekatan di 2 kotak bersebelahan (mis. \"6a\" "
    "di kotak ini, \"5b\" di kotak sebelahnya).\n"
    "7. \"kode\" dlm array WAJIB JSON string bertanda kutip ganda (termasuk "
    "\"0\"), atau null (tanpa kutip) kalau kosong.\n"
    "8. Output HARUS JSON valid saja, PERSIS 2 field \"jam_label\" dan "
    "\"kotak\".\n"
)